# Generated by Django 4.2 on 2024-03-01 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_image_caption_image_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='publish_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='publish_date',
            new_name='created_at',
        ),
    ]
