# Generated by Django 4.2 on 2024-03-05 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_story'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name_plural': 'Stories'},
        ),
    ]
