# Generated by Django 4.2 on 2024-03-05 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_story_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='PostImage',
        ),
    ]
