# Generated by Django 4.2 on 2024-03-06 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_profileview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileview',
            old_name='view_timestamp',
            new_name='created_at',
        ),
    ]
